version: "3.8"
services:

   mysql:
      image: mysql:8
      container_name: mysql
      ports:
         - 3306:3306
         - 33060:33060
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=bootdb
      networks:
         - quotation-management-network
      
   stockmanager:
      image: lucasvilela/stock-manager
      container_name: stockmanager
      ports:
         - 8080:8080
      networks:
         - quotation-management-network      
         
   quotationmanagement:
      build:
         dockerfile: ./Dockerfile
         context: ./
      image: leonardojunior/quotation-management
      container_name: quotation-management
      ports:
         - 8081:8081
      environment:
         - PORT=8081
         - MYSQL_CONTAINER=mysql
         - STOCK_MANAGER_CONTAINER=stockmanager
         - SPRING_PROFILES_ACTIVE=prod 
      networks:
         - quotation-management-network
      depends_on:
         - stockmanager
         - mysql

networks:
   quotation-management-network:
      driver: bridge